SRC_CPPS = \
           MyEventSink.cpp \
           MyRegisterEventSink.cpp \
           MyTriggerSource.cpp \
           SoftDeviceGEVTrigger.cpp \
           Utilities.cpp \

EXEC     = SoftDeviceGEVTrigger

include ../sample.Makefile
