SRC_CPPS = \
           ArrayFile.cpp \
           DiskFile.cpp \
           FileAccessEventSink.cpp \
           FileAccessRegisterEventSink.cpp \
           MyEventSink.cpp \
           MyRegisterEventSink.cpp \
           MySource.cpp \
           MyUserSetNotify.cpp \
           SoftDeviceGEV.cpp \
           Utilities.cpp \

EXEC     = SoftDeviceGEV

include ../sample.Makefile
