SRC_CPPS = \
           MyEventSink.cpp \
           MyRegisterEventSink.cpp \
           MySource.cpp \
           SoftDeviceGEVChunkData.cpp \
           Utilities.cpp \

EXEC     = SoftDeviceGEVChunkData

include ../sample.Makefile
